apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nuodb-docker-java-demo
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nuodb-docker-java-demo
  template:
    metadata:
      labels:
        app: nuodb-docker-java-demo
    spec:
      containers:
      - image: nuodb-docker-java-demo:1.0
        name: nuodb-docker-java-demo
        ports:
        - containerPort: 8888
